"""added wishlist

Revision ID: 30252296b28b
Revises: a3d20bc38ca5
Create Date: 2022-02-24 11:54:14.049216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30252296b28b'
down_revision = 'a3d20bc38ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Wishlist',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('ProductWishlist',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Products.ProductID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['Wishlist.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ProductWishlist')
    op.drop_table('Wishlist')
    # ### end Alembic commands ###
