"""gregiooigegiegpop

Revision ID: 55a10165d78c
Revises: fbbe95e38d47
Create Date: 2022-02-22 21:56:29.871097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55a10165d78c'
down_revision = 'fbbe95e38d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProductCart',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['Cart.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['Products.ProductID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('product_cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_cart',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['Cart.Id'], name='product_cart_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['Products.ProductID'], name='product_cart_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ProductCart')
    # ### end Alembic commands ###
